import "@fontsource/roboto/300.css"
import "@fontsource/roboto/400.css"
import "@fontsource/roboto/500.css"
import "@fontsource/roboto/700.css"

import type { Metadata } from "next"
import ThemeRegistry from "./ThemeRegistry"
import { SocketProvider } from "@/app/SocketProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SocketProvider>
          <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
        </SocketProvider>
      </body>
    </html>
  )
}
